services:
  - type: web
    name: linkedin-resume-optimizer-backend
    env: python
    buildCommand: pip install -r backend/requirements.txt && playwright install chromium
    startCommand: cd backend && uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: FRONTEND_URL
        sync: false
      - key: DEEPSEEK_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ENVIRONMENT
        value: production
      - key: PYTHON_VERSION
        value: 3.11.0
    healthCheckPath: /health
    autoDeploy: true